### ISSUE TITLE
Triet Minh Huynh

### ISSUE THREAD

**Issue by triethuynh2301** [MentorMentee/mentorship#2]
# Mentorship Request Form

## About Yourself
- Full Name: Triet Minh Huynh
- Education, Year: Bachelor of Science in Computer Science, 2019
- Coding Experience(Years): 2
- Connect with me at https://www.linkedin.com/in/anit, and mention you are requesting mentorship.

## Interested Area Of Programming
  - [x]  Backend Programming
    - [x] Java
    - [x] C#
    - [ ] Golang
    - [ ] Python
    - [ ] PHP
    - [x] JavaScript, TypeScript, NodeJS 
  - [ ] Platform Engineering (DevOps, SRE, System)
  - [x] Frontend Programming (JavaScript, TypeScript, ReactJS, Angular)
  - [ ] Frontend Design (HTML, CSS)
  - [ ] Mobile App
    - [ ] Android
    - [ ] iOS
    - [ ] Hybrid

---

# So what happens now?
Assign the issue to me, @codeanit.
![image](https://user-images.githubusercontent.com/414141/131242600-6efea115-6ba1-4a0a-a857-1ef3526010b4.png)

You and I, will have a conversation to get to know each other a bit more.

We will set a date for audio/video conversation via LinkedIn chat.

I will take note such as 
- Your area of interest.
- Your level of understanding in the area (Beginner/Intermediate/Advance).
- And we will choose a programming language for the mentorship.

I will create a repository for you where all the progress will be stored.

And these notes will be commented in this issue.

**Comment by codeanit** [comment]
@triethuynh2301 Please assign the task to me.

**Comment by anitsh** [comment]
@triethuynh2301 will not be able to commit full-time as he is committed to previous on-going learning, closing this issue for now.
